//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPPHELP
{
    using System;
    using System.Collections.Generic;
    
    public partial class KarandashiInventory
    {
        public string Тип_карандаша { get; set; }
        public string Размер { get; set; }
        public string Цвет { get; set; }
        public double Цена { get; set; }
    }
}
